version: '3'
services:
  go:
    container_name: docker_Go
    build:
      context: .
      dockerfile: Dockerfile
    command:  /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: go_database
      MYSQL_HOST: docker_MySQL  
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    container_name: docker_MySQL  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local